# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3ZOLdbOpNVI4Y_NWlaOk2ytwEx07Hg8
"""

# ========================================
# STEP 1: Upload CSV
# ========================================
from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt

# Upload the CSV (choose your sales.csv.csv file)
uploaded = files.upload()

# Load into Pandas DataFrame
df = pd.read_csv("sales.csv.csv")   # <-- make sure name matches uploaded file
print("✅ File Loaded Successfully")
print(df.head())

# ========================================
# STEP 2: Quick Data Overview
# ========================================
print("Shape of dataset:", df.shape)
print("\nInfo:")
print(df.info())
print("\nSummary statistics:")
print(df.describe())
print("\nMissing values:")
print(df.isnull().sum())

# ========================================
# STEP 3: Sales by Region
# ========================================
sales_by_region = df.groupby("Region")["Sales_Amount"].sum().sort_values(ascending=False)
print(sales_by_region)

sales_by_region.plot(kind="bar", figsize=(6,4))
plt.title("Total Sales by Region")
plt.ylabel("Sales Amount")
plt.show()

# ========================================
# STEP 4: Top 5 Sales Reps
# ========================================
top_reps = df.groupby("Sales_Rep")["Sales_Amount"].sum().sort_values(ascending=False).head(5)
print(top_reps)

top_reps.plot(kind="bar", color="orange", figsize=(6,4))
plt.title("Top 5 Sales Representatives")
plt.ylabel("Sales Amount")
plt.show()

# ========================================
# STEP 5: Sales by Product Category
# ========================================
sales_by_category = df.groupby("Product_Category")["Sales_Amount"].sum()
print(sales_by_category)

sales_by_category.plot(kind="bar", figsize=(6,4), color="green")
plt.title("Total Sales by Product Category")
plt.ylabel("Sales Amount")
plt.show()

# ========================================
# STEP 6: Monthly Sales Trend
# ========================================
df["Sale_Date"] = pd.to_datetime(df["Sale_Date"])
monthly_sales = df.groupby(df["Sale_Date"].dt.to_period("M"))["Sales_Amount"].sum()

monthly_sales.plot(kind="line", marker="o", figsize=(8,4))
plt.title("Monthly Sales Trend")
plt.ylabel("Sales Amount")
plt.xlabel("Month")
plt.show()

# ========================================
# STEP 7: Customer Type Comparison
# ========================================
customer_sales = df.groupby("Customer_Type")["Sales_Amount"].sum()
print(customer_sales)

customer_sales.plot(kind="bar", color=["skyblue","pink"], figsize=(5,4))
plt.title("Sales by Customer Type")
plt.ylabel("Sales Amount")
plt.show()

# ========================================
# STEP 8: Payment Method Distribution
# ========================================
payment_sales = df.groupby("Payment_Method")["Sales_Amount"].sum()
print(payment_sales)

payment_sales.plot(kind="pie", autopct="%1.1f%%", figsize=(5,5))
plt.title("Sales by Payment Method")
plt.ylabel("")
plt.show()